- name: Criando o diretório da app Giropops
  file: 
    path: "{{item}}"
    state: directory
  with_items:
    - /opt/giropops
    - /opt/giropops/logs
    - /opt/giropops/conf

- name: Copiando o arquivo de deployment da app para o host
  template:
    src: app_v1.yml.j2
    dest: /opt/giropops/giropops_v1.yml
    owner: root
    group: root
    mode: 0644
  register: copiando_template

- name: Copiando o arquivo de service da app para o host
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "files/service_app.yml", dest: "/opt/giropops/service_app.yml" }
  register: copiando_service_file

- name: Criando o deployment da app Giropops
  shell: "kubectl apply -f /opt/giropops/giropops_v1.yml"
  register: deploy_app

- name: Criando o service da app Giropops
  shell: "kubectl apply -f /opt/giropops/service_app.yml"
  register: deploy_service_app